update: add deployment job to CI workflow with secure token verification

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,8 @@ on:
   # Allows to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+permissions:
+  contents: read
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -37,3 +39,27 @@ jobs:
 
       - name: Run Linter
         run: flake8 .
+
+
+  deploy:
+    name: Deploy to Production
+    runs-on: ubuntu-latest
+
+    needs: lint
+
+    if: github.ref == 'refs/heads/main'
+
+    steps:
+      - name: Simulate secure Deployment
+        env:
+          API_TOKEN: ${{secrets.PRODUCTION_TOKEN}}
+        run: |
+          echo "Verification of prerequisites for deployment..."
+          
+          if [-z "$API_TOKEN"]; then
+            echo "CRITICAL ERROR: The production token is missing or empty."
+            exit 1
+          else 
+            echo "SUCCESS: Production token successfully injected into memory."
+            echo "Deployment in progess..."
+          fi
